# Generated by Django 6.0.2 on 2026-02-07 21:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDesertArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(help_text='Name of the food desert area', max_length=255)),
                ('latitude', models.FloatField(help_text='Latitude coordinate')),
                ('longitude', models.FloatField(help_text='Longitude coordinate')),
                ('address', models.CharField(blank=True, help_text='Full address of the area', max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('population', models.IntegerField(help_text='Total population', validators=[django.core.validators.MinValueValidator(0)])),
                ('poverty_rate', models.FloatField(help_text='Percentage of population in poverty', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('median_income', models.FloatField(help_text='Median household income', validators=[django.core.validators.MinValueValidator(0)])),
                ('distance_to_grocery', models.FloatField(help_text='Average distance to nearest grocery store in miles', validators=[django.core.validators.MinValueValidator(0)])),
                ('grocery_store_count', models.IntegerField(help_text='Number of grocery stores within service area', validators=[django.core.validators.MinValueValidator(0)])),
                ('has_public_transit', models.BooleanField(default=False, help_text='Has public transportation')),
                ('vehicle_ownership_rate', models.FloatField(help_text='Percentage of households with vehicle access', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('farmers_market_count', models.IntegerField(help_text='Number of farmers markets', validators=[django.core.validators.MinValueValidator(0)])),
                ('food_assistance_programs', models.IntegerField(help_text='Number of SNAP/WIC and other assistance programs', validators=[django.core.validators.MinValueValidator(0)])),
                ('unemployment_rate', models.FloatField(help_text='Unemployment rate percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('food_insecurity_rate', models.FloatField(help_text='Percentage of population with food insecurity', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('health_problems_rate', models.FloatField(help_text='Percentage with nutrition-related health problems', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_year', models.IntegerField(default=2024, help_text='Year of the data')),
            ],
            options={
                'verbose_name': 'Food Desert Area',
                'verbose_name_plural': 'Food Desert Areas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_level', models.CharField(choices=[('critical', 'Critical'), ('severe', 'Severe'), ('moderate', 'Moderate'), ('mild', 'Mild')], help_text='Severity level of food insecurity', max_length=20)),
                ('food_insecurity_score', models.FloatField(help_text='Overall food insecurity score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('accessibility_score', models.FloatField(help_text='Food accessibility score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('income_adequacy_score', models.FloatField(help_text='Income adequacy score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('infrastructure_score', models.FloatField(help_text='Infrastructure and transit score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('key_challenges', models.TextField(help_text='Major challenges identified')),
                ('recommendations', models.TextField(help_text='Detailed recommendations')),
                ('short_term_actions', models.TextField(help_text='Actions to take in next 6 months')),
                ('long_term_actions', models.TextField(help_text='Long-term strategies (1-3+ years)')),
                ('priority_solutions', models.JSONField(default=list, help_text='List of priority solutions with details')),
                ('estimated_investment', models.CharField(help_text="Estimated investment needed (e.g., '$500K-$1M')", max_length=50)),
                ('implementation_timeline', models.CharField(help_text='Expected timeline for implementation', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_version', models.IntegerField(default=1, help_text='Version of analysis algorithm used')),
                ('food_desert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='food_security.fooddesertarea')),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('retail', 'Retail & Store Development'), ('transportation', 'Transportation & Access'), ('income', 'Income Support & Jobs'), ('education', 'Education & Literacy'), ('assistance', 'Food Assistance Programs'), ('community', 'Community Development'), ('policy', 'Policy & Advocacy'), ('technology', 'Technology & Innovation')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rationale', models.TextField(help_text='Why this recommendation is important')),
                ('expected_impact', models.TextField(help_text='Expected outcomes and KPIs')),
                ('implementation_steps', models.JSONField(default=list, help_text='Step-by-step implementation plan')),
                ('required_resources', models.TextField(help_text='Required resources and partners')),
                ('success_metrics', models.JSONField(default=list, help_text='Metrics to measure success')),
                ('priority', models.IntegerField(default=3, help_text='Priority level (1=highest, 5=lowest)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feasibility', models.IntegerField(default=3, help_text='Feasibility level (1=very difficult, 5=very easy)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('estimated_cost', models.CharField(help_text='Estimated cost range', max_length=50)),
                ('timeline_months', models.IntegerField(help_text='Timeline in months')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_recommendations', to='food_security.analysisresult')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'ordering': ['priority', '-feasibility'],
            },
        ),
    ]
